[2023-05-01T16:05:17.452+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: space_missions_launches_to_gcp_dag.branch_task manual__2023-05-01T16:05:12.900478+00:00 [queued]>
[2023-05-01T16:05:17.457+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: space_missions_launches_to_gcp_dag.branch_task manual__2023-05-01T16:05:12.900478+00:00 [queued]>
[2023-05-01T16:05:17.457+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T16:05:17.457+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-01T16:05:17.457+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T16:05:17.472+0000] {taskinstance.py:1309} INFO - Executing <Task(_BranchPythonDecoratedOperator): branch_task> on 2023-05-01 16:05:12.900478+00:00
[2023-05-01T16:05:17.477+0000] {standard_task_runner.py:55} INFO - Started process 15375 to run task
[2023-05-01T16:05:17.479+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'space_missions_launches_to_gcp_dag', 'branch_task', 'manual__2023-05-01T16:05:12.900478+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/space_missions_launches_to_gcp.py', '--cfg-path', '/tmp/tmp17a6d8oy']
[2023-05-01T16:05:17.479+0000] {standard_task_runner.py:83} INFO - Job 102: Subtask branch_task
[2023-05-01T16:05:17.514+0000] {task_command.py:389} INFO - Running <TaskInstance: space_missions_launches_to_gcp_dag.branch_task manual__2023-05-01T16:05:12.900478+00:00 [running]> on host e47d5c97588c
[2023-05-01T16:05:17.557+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=space_missions_launches_to_gcp_dag
AIRFLOW_CTX_TASK_ID=branch_task
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T16:05:12.900478+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-01T16:05:12.900478+00:00
[2023-05-01T16:05:17.563+0000] {python.py:177} INFO - Done. Returned value was: space_missions_launches_from_gcs_to_bq_task
[2023-05-01T16:05:17.563+0000] {python.py:211} INFO - Branch callable return space_missions_launches_from_gcs_to_bq_task
[2023-05-01T16:05:17.563+0000] {skipmixin.py:155} INFO - Following branch space_missions_launches_from_gcs_to_bq_task
[2023-05-01T16:05:17.568+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 212, in execute
    self.skip_all_except(context["ti"], branch)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/skipmixin.py", line 186, in skip_all_except
    "'branch_task_ids' must contain only valid task_ids. "
airflow.exceptions.AirflowException: 'branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'space_missions_launches_from_gcs_to_bq_task'}.
[2023-05-01T16:05:17.570+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=space_missions_launches_to_gcp_dag, task_id=branch_task, execution_date=20230501T160512, start_date=20230501T160517, end_date=20230501T160517
[2023-05-01T16:05:17.581+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 102 for task branch_task ('branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'space_missions_launches_from_gcs_to_bq_task'}.; 15375)
[2023-05-01T16:05:17.611+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-01T16:05:17.622+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
